{
 "title": "Job Processor",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,15m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pending Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(worker_jobs_pending)" }
   ]
  },
  {
   "title": "Jobs per Second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(worker_jobs_processed_total[$interval]))"
    }
   ]
  },
  {
   "title": "Avg Processing Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(worker_jobs_process_time_seconds_sum[$interval]) / rate(worker_jobs_process_time_seconds_count[$interval]))"
    }
   ]
  },
  {
   "title": "Avg Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(worker_jobs_process_time_seconds_sum[$interval])) / sum(rate(worker_jobs_process_time_seconds_count[$interval]))",
     "legendFormat": "seconds"
    },
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by (le) (rate(worker_jobs_process_time_seconds_bucket[5m]))\n)",
     "legendFormat": "50% Percentile"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (rate(worker_jobs_process_time_seconds_bucket[5m]))\n)",
     "legendFormat": "95% Percentile"
    },
    {
     "expr": "histogram_quantile(\n  1.0,\n  sum by (le) (rate(worker_jobs_process_time_seconds_bucket[5m]))\n)",
     "legendFormat": "100% Percentile"
    }
   ]
  },
  {
   "title": "Rate of Job Queue Change",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (deriv(worker_jobs_pending[$interval]))",
     "legendFormat": "jobs"
    }
   ]
  },
  { "title": "Pending Job Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Pending Jobs Count Overall",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(worker_jobs_pending)", "legendFormat": "jobs" }
   ]
  },
  {
   "title": "Pending Jobs Count by Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(worker_jobs_pending) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Pending Jobs Count by Version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(worker_jobs_processed_total) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Pending Jobs QPS by Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type) (rate(worker_jobs_pending[$interval]))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Pending Jobs QPS by Version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (version) (rate(worker_jobs_pending[$interval]))",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  { "title": "Processed Job Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Processed Jobs Count Overall",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(worker_jobs_processed_total)",
     "legendFormat": "jobs"
    }
   ]
  },
  {
   "title": "Processed Jobs Count by Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(worker_jobs_processed_total) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Processed Jobs Count by Version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(worker_jobs_processed_total) by (version)",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Processed Jobs QPS by Type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type) (rate(worker_jobs_processed_total[$interval]))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Processed Jobs QPS by Version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (version) (rate(worker_jobs_processed_total[$interval]))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  { "title": "Stats by Worker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "# Processed per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum by (worker_id) (rate(worker_jobs_processed_total[$interval]))",
     "legendFormat": "Worker #{{ worker_id }}"
    }
   ]
  },
  {
   "title": "Avg Process Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "sum by (worker_id) (rate(worker_jobs_process_time_seconds_sum[$interval])) / sum by (worker_id) (rate(worker_jobs_process_time_seconds_count[$interval]))",
     "legendFormat": "Worker #{{ worker_id }}"
    }
   ]
  },
  { "title": "Stats by Job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "# Processed per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum by (type) (rate(worker_jobs_processed_total[$interval]))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Avg Process time per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "sum by (type) (rate(worker_jobs_process_time_seconds_sum[$interval])) / sum by (type) (rate(worker_jobs_process_time_seconds_count[$interval]))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Pending Jobs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum by (type) (rate(worker_jobs_processed_total[$interval]))"
    }
   ]
  },
  {
   "title": "Rate of Job Queue change",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "sum by (type) (deriv(worker_jobs_inflight[$interval]))"
    }
   ]
  }
 ]
}